name = "aoc"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
party = ">= 1.0.4 and < 2.0.0"
clip = ">= 0.1.0 and < 1.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_yielder = ">= 1.0.0 and < 2.0.0"
nibble = ">= 1.1.1 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
parallel_map = ">= 2.1.0 and < 3.0.0"
rememo = ">= 3.1.0 and < 4.0.0"
pocket_watch = ">= 1.0.0 and < 2.0.0"
gleamy_structures = ">= 1.1.0 and < 2.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gary = ">= 1.1.0 and < 2.0.0"
gleam_crypto = ">= 1.4.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck = ">= 0.0.6 and < 1.0.0"
